### ISSUE TITLE
 No such file or directory: '../exps/shapenet_psr_validation_set/airplane_02691156_404_samples.npz

### ISSUE THREAD

**Issue by kiritojoj** [SLIDE-3D/SLIDE#5]
Hi@Zhaoyang Lyu, I have successfully followed the steps to configure the environment,

but when I run my script to use autoencoder:

export CUDA_VISIBLE_DEVICES=0 && python autoencoder_encode.py --ckpt ../exps/mesh_overall_ckpts_and_generation_results/autoencoder_models/add_centroid_as_first_keypoint/lamp/pointnet_ckpt_106679.pkl \ 
--batch_size 200 --save_dir ../exps/generated_point_cloud/lamp/centroid 

I get the following error:

Traceback (most recent call last):
  File "autoencoder_encode.py", line 108, in <module>
    test_dataset = GeneralNpzDataset(args.dataset_path, scale=1, noise_magnitude=0, rank=0, world_size=1, 
  File "/home/chenjian/Project/SLIDE/pointnet2/sampling_and_inference/../shapenet_psr_dataloader/npz_dataset.py", line 69, in __init__
    data = np.load(data_dir)
  File "/home/chenjian/.conda/envs/slide/lib/python3.8/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
**FileNotFoundError: [Errno 2] No such file or directory: '../exps/shapenet_psr_validation_set/airplane_02691156_404_samples.npz'**

I wonder how I should get this .npz file and fix this error.
thanks!

**Comment by FerCanAra** [comment]
I have the same problem!

**Comment by icedCoffe001** [comment]
I have the same problem!
